name: ui_guard
description: A simple and flexible role-based UI control plugin for Flutter.
repository: https://github.com/Tanvirul-swe/ui_guard
issue_tracker: https://github.com/Tanvirul-swe/ui_guard/issues

version: 1.0.1
homepage: https://tanvirdev.com

topics: [
  flutter,
  plugin,
  user,
  role-based,
  access-control
]

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
