name: ui_guard
description: A simple and flexible role-based UI control plugin for Flutter.
version: 1.0.0
homepage: https://github.com/Tanvirul-swe/ui_guard 

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
